server:
  port: 1855
mybatis:
    mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vms?useSSL=false&serverTimezone=UTC
    username: root
    password: ibm11ibm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
  activiti:
    database-schema-update: true
    check-process-definitions: false
    activiti5CompatibilityEnabled: true
  main: 
    allow-bean-definition-overriding: true
  
