server:
  port: 1855

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: passw0rd4vms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
  activiti:
    database-schema-update: true
    check-process-definitions: false
  main: 
    allow-bean-definition-overriding: true
